#!/bin/sh
# Install to /opt/hdhr3-proxy and enable the service. Run as root.
set -e
[ "$(id -u)" = 0 ] || { echo "run as root"; exit 1; }
cd "$(dirname "$0")"

command -v hdhomerun_config >/dev/null || {
    echo "hdhomerun_config not found. Install it first, e.g.:"
    echo "  Debian/Ubuntu : apt install hdhomerun-config"
    echo "  Fedora        : dnf install libhdhomerun"
    echo "  Arch          : pacman -S libhdhomerun"
    echo "  Gentoo        : emerge media-libs/libhdhomerun"
    exit 1; }

# DATA_DIR comes from the config being installed, or from one already in place
DATA_DIR=/var/lib/hdhr3-proxy
[ -f /opt/hdhr3-proxy/hdhr3-proxy.conf ] && . /opt/hdhr3-proxy/hdhr3-proxy.conf
[ -f ./hdhr3-proxy.conf ] && [ ! -f /opt/hdhr3-proxy/hdhr3-proxy.conf ] && . ./hdhr3-proxy.conf
: "${DATA_DIR:=/var/lib/hdhr3-proxy}"

id hdhr3-proxy >/dev/null 2>&1 || useradd --system --home "$DATA_DIR" --shell /usr/sbin/nologin hdhr3-proxy
install -d -o hdhr3-proxy -g hdhr3-proxy "$DATA_DIR"
install -d /opt/hdhr3-proxy
install -m 0644 hdhr3_proxy.py hdhr3_epg.py check_guide.py README.md /opt/hdhr3-proxy/
install -m 0755 run.sh check.sh /opt/hdhr3-proxy/
[ -f /opt/hdhr3-proxy/hdhr3-proxy.conf ] || install -m 0644 hdhr3-proxy.conf /opt/hdhr3-proxy/
# Refuse a unit left over from before the hdhr3 -> hdhr3-proxy rename: it
# names a user and paths that no longer exist, and systemd fails with 217/USER.
for bad in 'ExecStart=/opt/hdhr3/' 'User=hdhr3$' 'WorkingDirectory=/opt/hdhr3$'; do
    if grep -qE "$bad" hdhr3-proxy.service; then
        echo "ERROR: hdhr3-proxy.service in $(pwd) is a stale pre-rename copy"
        echo "       (matches '$bad'). Replace it with the current one."
        exit 1
    fi
done
install -m 0644 hdhr3-proxy.service /etc/systemd/system/
systemctl daemon-reload

# and verify what is now installed can actually start
unit_user=$(awk -F= '/^User=/{print $2}' /etc/systemd/system/hdhr3-proxy.service)
id "$unit_user" >/dev/null 2>&1 || {
    echo "ERROR: the unit runs as '$unit_user', which does not exist."; exit 1; }
unit_exec=$(awk -F= '/^ExecStart=/{print $2}' /etc/systemd/system/hdhr3-proxy.service)
[ -x "$unit_exec" ] || {
    echo "ERROR: the unit runs '$unit_exec', which is not executable."; exit 1; }

# Carry over anything already generated by testing, so the service does not
# start with a fresh channel scan and a full EPG grab.
moved=""
for f in muxes.json services.json epg-cache.json guide.xml; do
    for src in "./$f" "${DATA_DIR%/}/../$f"; do
        [ -f "$src" ] || continue
        [ -f "$DATA_DIR/$f" ] && continue
        install -m 0644 -o hdhr3-proxy -g hdhr3-proxy "$src" "$DATA_DIR/$f"
        moved="$moved $f"
        break
    done
done
[ -n "$moved" ] && echo "carried over into $DATA_DIR:$moved"
chown -R hdhr3-proxy:hdhr3-proxy "$DATA_DIR"

echo
echo "Edit /opt/hdhr3-proxy/hdhr3-proxy.conf (DEVICE, SOURCE, OPTIONS), then:"
echo "  /opt/hdhr3-proxy/check.sh"
echo "  systemctl enable --now hdhr3-proxy"
echo "  journalctl -fu hdhr3-proxy"
